# Generated by Django 3.2.8 on 2022-06-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название канала')),
                ('link', models.CharField(max_length=100, verbose_name='Ссылка')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название чата')),
            ],
            options={
                'verbose_name': 'Гильдия',
                'verbose_name_plural': 'Гильдии',
            },
        ),
        migrations.CreateModel(
            name='DontShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.CharField(max_length=50, verbose_name='user_1')),
                ('user_2', models.CharField(max_length=50, verbose_name='user_2')),
            ],
            options={
                'verbose_name': 'Не показывать в нетворкинге (для телеграма)',
                'verbose_name_plural': 'Не показывать в нетворкинге (для телеграма)',
            },
        ),
        migrations.CreateModel(
            name='User_tg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('tg_id', models.TextField(verbose_name='tg_id')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('photo', models.TextField(null=True, verbose_name='photo_id')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('family', models.CharField(max_length=100, verbose_name='family')),
                ('admire', models.CharField(max_length=100, verbose_name='admire')),
                ('hobbi', models.CharField(max_length=100, verbose_name='hobbi')),
                ('name_company', models.CharField(max_length=100, verbose_name='name_company')),
                ('site', models.CharField(max_length=100, verbose_name='site')),
                ('industri', models.TextField(verbose_name='industri')),
                ('region', models.CharField(max_length=100, verbose_name='region')),
                ('mpy', models.TextField(verbose_name='money per year')),
                ('staf_count', models.TextField(verbose_name='staf count')),
                ('filial_count', models.CharField(max_length=100, verbose_name='filial_count')),
                ('role', models.CharField(max_length=100, verbose_name='role')),
                ('model_evolution', models.CharField(max_length=100, verbose_name='model_evolution')),
                ('attention', models.CharField(max_length=100, verbose_name='attention')),
                ('skills', models.CharField(max_length=100, verbose_name='skills')),
            ],
            options={
                'verbose_name': 'Пользователь тг',
                'verbose_name_plural': 'Пользователи тг',
                'db_table': 'work_users',
            },
        ),
    ]
