# Generated by Django 3.2.8 on 2022-06-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tg',
            name='chat',
            field=models.CharField(default=0, max_length=50, verbose_name='chat'),
            preserve_default=False,
        ),
    ]
