# Generated by Django 3.2.8 on 2022-07-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_channel_tg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_tg',
            name='admire',
        ),
        migrations.RemoveField(
            model_name='user_tg',
            name='attention',
        ),
        migrations.RemoveField(
            model_name='user_tg',
            name='family',
        ),
        migrations.RemoveField(
            model_name='user_tg',
            name='filial_count',
        ),
        migrations.RemoveField(
            model_name='user_tg',
            name='hobbi',
        ),
        migrations.RemoveField(
            model_name='user_tg',
            name='industri',
        ),
        migrations.RemoveField(
            model_name='user_tg',
            name='model_evolution',
        ),
        migrations.RemoveField(
            model_name='user_tg',
            name='mpy',
        ),
        migrations.RemoveField(
            model_name='user_tg',
            name='name_company',
        ),
        migrations.RemoveField(
            model_name='user_tg',
            name='region',
        ),
        migrations.RemoveField(
            model_name='user_tg',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user_tg',
            name='site',
        ),
        migrations.RemoveField(
            model_name='user_tg',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='user_tg',
            name='staf_count',
        ),
        migrations.AddField(
            model_name='user_tg',
            name='about',
            field=models.TextField(default=0, verbose_name='about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_tg',
            name='about_1',
            field=models.TextField(default=0, verbose_name='about_1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_tg',
            name='about_2',
            field=models.TextField(default=0, verbose_name='about_2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_tg',
            name='about_3',
            field=models.TextField(default=0, verbose_name='about_3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_tg',
            name='about_4',
            field=models.TextField(default=0, verbose_name='about_4'),
            preserve_default=False,
        ),
    ]
