# Generated by Django 3.2.8 on 2022-07-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_ivent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ivent',
            old_name='link',
            new_name='date',
        ),
    ]
