# Generated by Django 3.2.8 on 2022-06-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_user_tg_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='link',
            field=models.CharField(default=0, max_length=50, verbose_name='link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='tg_id',
            field=models.CharField(default=0, max_length=50, verbose_name='tg_id'),
            preserve_default=False,
        ),
    ]
