# Generated by Django 3.2.8 on 2022-06-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_remove_channel_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='tg_id',
            field=models.CharField(default=0, max_length=50, verbose_name='tg_id'),
            preserve_default=False,
        ),
    ]
