# Generated by Django 3.2.8 on 2022-07-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20220704_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ivent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_ivent', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('photo', models.TextField()),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
