# Generated by Django 3.2.8 on 2022-07-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_rename_link_ivent_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from', models.CharField(max_length=100)),
                ('user_to', models.CharField(max_length=100)),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name': 'Таск',
                'verbose_name_plural': 'Таски',
            },
        ),
    ]
