# Generated by Django 3.2.8 on 2022-07-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_taskconnect'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tg',
            name='about',
            field=models.TextField(default='Информация для нетворкинга'),
            preserve_default=False,
        ),
    ]
